Parameters:
  AppName:
    Type: String
    Description: The name associate with the project

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub ${AWS::Region}a
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub ${AWS::Region}b
      CidrBlock: 10.0.16.0/24
      MapPublicIpOnLaunch: true
  PublicSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub ${AWS::Region}c
      CidrBlock: 10.0.32.0/24
      MapPublicIpOnLaunch: true
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  RouteTrafficToIGW:
    Type: AWS::EC2::Route
    DependsOn:
      - AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0
  PublicSubnetRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable
  PublicSubnetRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable
  PublicSubnetRouteTableAssociationC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetC
      RouteTableId: !Ref PublicRouteTable
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${AppName}-repo
  ServerCluster: 
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${AppName}-cluster
      CapacityProviders:
        - FARGATE

Outputs:
  VpcId:
    Description: The unique identifier of the VPC
    Value: !Ref VPC
    Export: 
      Name: VPC
  PublicSubnetA:
    Description: The unique identifier of the Public Subnet A
    Value: !Ref PublicSubnetA
    Export: 
      Name: PublicSubnetA
  PublicSubnetB:
    Description: The unique identifier of the Public Subnet B
    Value: !Ref PublicSubnetB
    Export: 
      Name: PublicSubnetB
  PublicSubnetC:
    Description: The unique identifier of the Public Subnet C
    Value: !Ref PublicSubnetC
    Export: 
      Name: PublicSubnetC
  ECSClusterResourceName:
    Description: ECS Cluster ARN
    Value: !GetAtt ServerCluster.Arn
    Export: 
      Name: Cluster
  ECRRepositoryResourceName:
    Description: ECR Repository ARN
    Value: !GetAtt ECRRepository.Arn
    Export: 
      Name: ECRRepository
  ECRRepositoryName:
    Description: Name of the private ECR Repository
    Value: !Ref ECRRepository