---
Parameters:
  UserName:
    Type: String
    Description: The name of the IAM user for the access key
  HealthCheckPath:
    Type: String
    Default: /
    Description: Health Check path for the container
  ContainerPort:
    Type: Number
    Default: 80
    Description: Open Port for the container

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub ${AWS::Region}a
      CidrBlock: 10.0.0.0/16
      MapPublicIpOnLaunch: true
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub ${AWS::Region}b
      CidrBlock: 10.0.16.0/16
      MapPublicIpOnLaunch: true
  PublicSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub ${AWS::Region}c
      CidrBlock: 10.0.32.0/16
      MapPublicIpOnLaunch: true
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  RouteTrafficToIGW:
    Type: AWS::EC2::Route
    DependsOn:
      - InternetGateway
      - AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0
  PublicSubnetRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable
  PublicSubnetRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable
  PublicSubnetRouteTableAssociationC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetC
      RouteTableId: !Ref PublicRouteTable

  User:
    Type: AWS::IAM:User
    Properties:
      UserName: !Ref UserName
  MyAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref User
      Status: 'Active'
  UserInlinePolicy:
    Type: AWS::IAM:Policy
    DependsOn:
      - ECRRepository
    Properties:
      PolicyName: !Sub ${AWS::StackName}-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'ECR'
            Effect: 'Allow'
            Action:
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:UploadLayerPart'
              - 'ecr:CompleteLayerUpload'
              - 'ecr:PutImage'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchImportUpstreamImage'
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:GetImageCopyStatus'
            Resource: !GetAtt ECRRepository.Arn
          - Effect: 'Allow'
            Action:
              - 'ecr:GetAuthorizationToken'
            Resource: '*'
          - Sid: 'RegisterTaskDefinition'
            Effect: 'Allow'
            Action:
              - ecs:RegisterTaskDefinition
            Resource: '*'
          - Sid: 'PassRolesInTaskDefinition'
            Effect: 'Allow'
            Action:
              - iam:PassRole
            # Resource: ""
          - Sid: 'DeployService'
            Effect: 'Allow'
            Action:
              - 'ecs:UpdateService'
              - 'ecs:DescribeServices'
            # Resource: ""
      User:
        - !Ref User
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${AWS::StackName}-repo
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - HttpTargetGroup
      # - ALBListenerRule
    Properties:
      RequiresCompatibilities:
        - FARGATE
      Family: !Sub ${AWS::StackName}
      ContainerDefinitions:
        - name: !Sub ${AWS::StackName}
          Image: !Join 
            - ':'
            - - !Join 
                - /
                - - !GetAtt ECRRepository.Arn
                  - !Ref ECRRepository
              - latest
          Essential: true
          PortMappings:
            - HostPort: !Ref ContainerPort
              protocol: tcp
              ContainerPort: !Ref ContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Join 
                - /
                - ecs
                  - !Sub ${AWS::StackName}
              awslogs-region: us-east-2
              awslogs-stream-prefix: ecs
      NetworkMode: awsvpc
      Memory: '512'
      Cpu: '256'
      # TaskRoleArn: !Ref ECSTaskRoleArn
      # ExecutionRoleArn: !Ref ECSTaskExecutionRoleArn

  HttpTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AWS::StackName}-tg
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      # VpcId: !Ref VpcId
      TargetType: ip
  # ALBListenerRule:
  #   Type: AWS::ElasticLoadBalancingV2::Listener
  ECSService:
    # Type: 'AWS::ECS::Service'
    # DependsOn: TaskDefinition
    # Properties:
    #   ServiceName: !Ref ECSServiceName
  

Outputs:
  UserAccessKeyId:
    Description: User access key ID
    Value: !GetAtt MyAccessKey.Id
  UserAccessKeySecret:
    Description: User secret access key
    Value: !GetAtt MyAccessKey.SecretAccessKey
